name: Dubem CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install flake8
      run: |
        pip install flake8

    - name: Run flake8 on main.py
      run: |
        flake8 main.py

    - name: Run Python script
      run: |
        python main.py
